### PR TITLE
Feature/cp yaml

### PR DESCRIPTION
**Pull request by aerorahul**
adding tests and renaming utils.py to file_utils.py

### CODE REVIEW

**Review by CoryMartin-NOAA — APPROVED** [review]

**Comment by aerorahul** [comment]
what conflicts is GH complaining about?

**Comment by CoryMartin-NOAA** [comment]
No idea... and your commit is in the log when I pull it locally, but not in the PR to the auth repo...

**Comment by aerorahul** [comment]
bizarre

**Comment by CoryMartin-NOAA** [comment]
an empty commit to my branch did the trick...

**Pull request merged**
